FROM ubuntu:22.04

RUN apt-get update && apt-get install -y \
    clang llvm make gcc git pkg-config \
    libbpf-dev libelf-dev \
    linux-libc-dev \
    linux-tools-common linux-tools-generic \
    python3 python3-pip && \
    apt-get clean

RUN ln -s /usr/lib/linux-tools-*/bpftool /usr/local/bin/bpftool || true
RUN pip3 install kubernetes

WORKDIR /app

COPY filter_connect_cgroup.c Makefile controller.py entrypoint.sh ./

RUN make
RUN chmod +x /app/entrypoint.sh

ENTRYPOINT ["/app/entrypoint.sh"]
