#include <stdio.h>
#include <unistd.h>
#include <bpf/libbpf.h>
#include "filter_connect_bpf.skel.h" // skeleton generated by bpftool

int main() {
    struct filter_connect_bpf *skel;
    int err;

    libbpf_set_strict_mode(LIBBPF_STRICT_ALL);

    skel = filter_connect_bpf__open();
    if (!skel) return 1;

    err = filter_connect_bpf__load(skel);
    if (err) return 1;

    err = filter_connect_bpf__attach(skel);
    if (err) return 1;

    printf("[+] LSM connect filter loaded.\n");
    while (1) pause();
}
