apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: filter
spec:
  selector:
    matchLabels:
      name: filter
  template:
    metadata:
      labels:
        name: filter
    spec:
      hostPID: true
      hostNetwork: true
      containers:
      - name: filter
        image:  jjyoung22/filtering:1.0
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN","SYS_RESOURCE","NET_ADMIN","BPF","SYS_PTRACE", "PERFMON"]
        volumeMounts:
        - name: bpf
          mountPath: /sys/fs/bpf
        - name: modules
          mountPath: /lib/modules
        - name: src
          mountPath: /usr/src
        - name: tracefs
          mountPath: /sys/kernel/debug
          readOnly: false
      volumes:
      - name: bpf
        hostPath:
          path: /sys/fs/bpf
      - name: modules
        hostPath:
          path: /lib/modules
      - name: src
        hostPath:
          path: /usr/src
      - name: tracefs
        hostPath:
          path: /sys/kernel/debug
